#所有请求的前缀
server:
  servlet:
    context-path: /sell

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Yuxuelian-520
    url: jdbc:mysql://118.126.108.24:3306/wx_order_food?useSSL=false&characterEncode=UTF-8
  jpa:
    show-sql: true
  jackson:
    #全局配置当某些属性是null的时候不返回到前端
    default-property-inclusion: non_null

#mybatis.config-location=classpath:mybatis-config.xml
#mybatis.mapper-locations=classpath:/mapper/**/*.xml
#mybatis.type-aliases-package=com.example.demo.repository.dao

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.repository.dao

