#所有请求的前缀
server:
  servlet:
    context-path: /sell

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Yuxuelian-520
    url: jdbc:mysql://118.126.108.24:3306/wx_order_food?useSSL=false&characterEncode=UTF-8
  jpa:
    show-sql: true
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.repository.dao

